update
Signed-off-by: james <open4pd@4paradigm.com>

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -26,18 +26,22 @@ jobs:
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3
 
-    - name: Docker Login
+    - name: Check Docker Secrets
+      if: ${{ secrets.DOCKERHUB_TOKEN == '' || secrets.DOCKERHUB_PASSWD == '' }}
       run: |
-        echo ${{ secrets.DOCKERHUB_PASSWD }} | docker login -u ${{ secrets.DOCKERHUB_TOKEN }} --password-stdin
-      #uses: docker/login-action@v3.6.0
-      #with:
-      #    # Server address of Docker registry. If not set then will default to Docker Hub
-      #    # registry: 4pdosc
-      #    # Username used to log against the Docker registry
-      #    username: ${{ secrets.DOCKERHUB_TOKEN }}
-      #    # Password or personal access token used to log against the Docker registry
-      #    password: ${{ secrets.DOCKERHUB_PASSWD }}
-      #    logout: false
+        echo "❌ Missing docker secrets. Set DOCKERHUB_TOKEN and DOCKERHUB_PASSWD!"
+        exit 1
+
+    - name: Docker Login
+      uses: docker/login-action@v3.6.0
+      with:
+          # Server address of Docker registry. If not set then will default to Docker Hub
+          # registry: 4pdosc
+          # Username used to log against the Docker registry
+          username: ${{ secrets.DOCKERHUB_TOKEN }}
+          # Password or personal access token used to log against the Docker registry
+          password: ${{ secrets.DOCKERHUB_PASSWD }}
+          logout: false
 
     - name: Build and push
       uses: docker/build-push-action@v6.18.0
